---

- apt_key: url=https://updates.signal.org/desktop/apt/keys.asc state=present
- apt_repository: repo='deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main' state=present update_cache='yes'
- apt: name='signal-desktop' state='present' update_cache='yes'

- name: install thunderbird
  apt: pkg=thunderbird state=latest
