---
- name: create bin directory if required...
  file:
    path: '~/bin'
    state: directory
    mode: 0700

- name: kubectl download
  get_url:
    url: 'https://storage.googleapis.com/kubernetes-release/release/v1.14.6/bin/linux/amd64/kubectl'
    dest: ~/bin/
    checksum: 'sha256:5f8e8d8de929f64b8f779d0428854285e1a1c53a02cc2ad6b1ce5d32eefad25c'

- name: kubectl set executable
  file: dest=~/bin/kubectl mode=a+x

- name: kubetpl download
  get_url:
    url: 'https://github.com/shyiko/kubetpl/releases/download/0.7.1/kubetpl-0.7.1-linux-amd64'
    dest: ~/bin/kubetpl
    checksum: 'sha256:46e982db7487df997ce6ae2e739f198a0868d4bb00f46a578610c02162e20dd5'

- name: kubetpl set executable
  file: dest=~/bin/kubetpl mode=a+x

- name: kustomize download
  get_url:
    url: 'https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.8.4/kustomize_v3.8.4_linux_amd64.tar.gz'
    dest: /tmp/kustomize.tar.gz
    checksum: 'sha256:194caffbdb59d8fc887488ba8fa3dce7b68ccf816737b57bde7338ca980f4912'

- name: create bin directory if required...
  file:
    path: '~/bin'
    state: directory
    mode: 0700

- name: kustomize unarchive
  unarchive:
    remote_src: yes
    src: /tmp/kustomize.tar.gz
    dest: '~/bin'
