---
- name: create bin directory if required...
  become: true
  become_user: "{{ main_user }}"
  file:
    path: '~/bin'
    state: directory
    mode: 0700

- name: kubectl download
  become: true
  become_user: "{{ main_user }}"
  get_url:
    url: 'https://dl.k8s.io/v1.24.2/bin/linux/amd64/kubectl'
    dest: ~/bin/
    checksum: 'sha256:f15fb430afd79f79ef7cf94a4e402cd212f02d8ec5a5e6a7ba9c3d5a2f954542'

- name: kubectl set executable
  become: true
  become_user: "{{ main_user }}"
  file: dest=~/bin/kubectl mode=a+x

- name: kubetpl download
  become: true
  become_user: "{{ main_user }}"
  get_url:
    url: 'https://github.com/shyiko/kubetpl/releases/download/0.7.1/kubetpl-0.7.1-linux-amd64'
    dest: ~/bin/kubetpl
    checksum: 'sha256:46e982db7487df997ce6ae2e739f198a0868d4bb00f46a578610c02162e20dd5'

- name: kubetpl set executable
  become: true
  become_user: "{{ main_user }}"
  file: dest=~/bin/kubetpl mode=a+x

- name: kustomize download
  become: true
  become_user: "{{ main_user }}"
  get_url:
    url: 'https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.4/kustomize_v4.5.4_linux_amd64.tar.gz'
    dest: /tmp/kustomize.tar.gz
    checksum: 'sha256:1159c5c17c964257123b10e7d8864e9fe7f9a580d4124a388e746e4003added3'

- name: create bin directory if required...
  become: true
  become_user: "{{ main_user }}"
  file:
    path: '~/bin'
    state: directory
    mode: 0700

- name: kustomize unarchive
  become: true
  become_user: "{{ main_user }}"
  unarchive:
    remote_src: yes
    src: /tmp/kustomize.tar.gz
    dest: '~/bin'
