---

- name: add nextcloud client ppa
  apt_repository: repo='ppa:nextcloud-devs/client' codename='xenial'

- name: install nextcloud client
  apt: pkg=nextcloud-client state=latest

- name: start nextcloud client
  become: true
  become_user: "{{ ansible_env.USER }}"
  shell: 'nextcloud &'
