---
- name: install battery status
  apt: pkg=i3xrocks-battery state=latest

- name: create regolith config dir
  become: true
  become_user: ps
  file: path=~/.config/regolith/i3 state=directory

- name: link i3 config from github profile files
  become: true
  become_user: ps
  file: src=~/git/psunix/profile/regolith/i3/config dest=~/.config/regolith/i3/config state=link
