---
- name: install battery status
  apt: pkg=i3xrocks-battery state=latest

- name: create regolith config dir
  file: path=/home/ps/.config/regolith/i3 state=directory

- name: link i3 config from github profile files
  file: src=/home/ps/git/psunix/profile/regolith/i3/config dest=/home/ps/.config/regolith/i3/config state=link
