---
- name: Add Regolith PPA GPG key
  apt_key:
    url: https://regolith-desktop.org/regolith.key
  when: ansible_distribution_version == '22.04'

- name: add regolith repository
  apt_repository: repo='deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main"' state=present
  when: ansible_distribution_version == '22.04'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Regolith desktop
  apt:
    name: regolith-desktop
    state: present

- name: Install additional Regolith packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - i3xrocks-net-traffic
    - i3xrocks-battery
