---

- name: add regolith repo
  apt_repository: repo='ppa:regolith-linux/release' codename='bionic'

- name: install regolith-desktop
  apt: pkg=regolith-desktop state=latest

- name: install i3xrocks-net-traffic
  apt: pkg=i3xrocks-net-traffic state=latest

- name: install i3xrocks-cpu-usage
  apt: pkg=i3xrocks-cpu-usage state=latest

- name: install i3xrocks-time
  apt: pkg=i3xrocks-time state=latest

- name: create i3 config dir
  file: path="{{ ansible_env.HOME }}/.i3" state=directory

- name: link i3 config from github profile files
  file: src="{{ ansible_env.HOME }}/git/psunix/profile/i3/config" dest="{{ ansible_env.HOME}}/.i3/config" state=link

- name: link lock background image
  file: src="{{ ansible_env.HOME }}/git/psunix/profile/i3/lock-bg.png" dest="{{ ansible_env.HOME}}/.i3/lock-bg.png" state=link
