---

- name: install vim
  apt: pkg=vim state=latest

- name: clone vim config
  become: true
  become_user: ps
  git: repo=https://github.com/psunix/dot-vim.git dest="/home/ps/.vim" update=yes

- name: Create backup dir
  become: true
  become_user: ps
  file:
    path: /home/ps/.vim/backup
    state: directory

- name: create config symlink
  become: true
  become_user: ps
  file: path=/home/ps/.vimrc
        src=/home/ps/.vim/vimrc
        state=link
        force=yes

- name: install vim plugins
  become: true
  become_user: ps
  shell: 'vim +"source ~/.vimrc" +"PlugInstall --sync" +qa'

- name: update vim plugins
  become: true
  become_user: ps
  shell: 'vim +"source ~/.vimrc" +"PlugUpdate --sync" +qa'
