---

- name: install vim
  apt: pkg=vim state=latest

- name: clone vim config
  become: true
  become_user: "{{ main_user }}"
  git: repo=https://github.com/psunix/dot-vim.git dest="~/.vim" update=yes

- name: Create backup dir
  become: true
  become_user: "{{ main_user }}"
  file:
    path: ~/.vim/backup
    state: directory

# - name: install vim plugins
  # become: true
  # become_user: "{{ main_user }}"
  # shell: 'vim -u ~/.vim/vimrc-setup +"PlugInstall --sync" +qa'

# - name: update vim plugins
  # become: true
  # become_user: "{{ main_user }}"
  # shell: 'vim +"PlugUpdate --sync" +qa'

- name: create config symlink
  become: true
  become_user: "{{ main_user }}"
  file: path=~/.vimrc
        src=~/.vim/vimrc
        state=link
        force=yes
