---

- name: install vim
  apt: pkg=vim state=latest

- name: clone vim config
  become: false
  git: repo=https://github.com/psunix/dot-vim.git dest="{{ ansible_env.HOME }}/.vim" update=yes

- name: create config symlink
  become: false
  file: path="{{ ansible_env.HOME }}/.vimrc"
        src="{{ ansible_env.HOME }}/.vim/vimrc"
        state=link
        force=yes

- name: install vim plugins
  become: true
  become_user: "{{ ansible_env.USER }}"
  shell: 'vim +"source ~/.vimrc" +"PlugInstall --sync" +qa'

- name: update vim plugins
  become: true
  become_user: "{{ ansible_env.USER }}"
  shell: 'vim +"source ~/.vimrc" +"PlugUpdate --sync" +qa'
