---
- name: install nitrokey app
  apt: pkg=nitrokey-app state=latest

- name: install nitrokey cli
  apt: pkg=nitrocli state=latest

# - name: install openpgp support for nitrokey
  # apt: pkg=libccid state=latest
