---

- name: ensure repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repository
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu jammy stable' state=present

- name: install docker
  apt: pkg=docker-ce state=latest

- name: install docker cli
  apt: pkg=docker-ce-cli state=latest

- name: install containerd.io
  apt: pkg=containerd.io state=latest

- name: install docker-buildx-plugin
  apt: pkg=docker-buildx-plugin state=latest

- name: install docker compose plugin
  apt: pkg=docker-compose-plugin state=latest

- name: add current user to docker group
  user: name="{{ main_user }}"
        groups=docker
        append=yes
