---

- name: ensure repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repository
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu xenial stable' state=present

- name: install docker
  apt: pkg=docker-ce state=latest

- name: remove legacy docker compose
  file:
    dest: "/usr/local/bin/docker-compose"
    state: absent

- name: install docker compose
  apt: pkg=docker-compose state=latest

- name: add current user to docker group
  user: name={{ ansible_env.USER }}
        groups=docker
        append=yes
