---

- name: psunix desktop environment playbook
  hosts: localhost
  roles:
    - { role: profile }
    - { role: nextcloud, become: true }
    - { role: i3, become: true }
    # devel tools
    - { role: vim, become: true }
    - { role: firefox, become: true }
    - { role: chromium, become: true }
    - { role: audio, become: true }
    - { role: display, become: true }
