---

- name: psunix desktop environment playbook
  hosts: localhost
  roles:
    - { role: profile }
    - { role: nextcloud, become: true }
    - { role: i3, become: true }
    # devel tools
    - { role: vim, become: true }
    - { role: firefox, become: true }
    - { role: chromium, become: true }
    - { role: audio, become: true }
    - { role: display, become: true }
    - { role: docker, become: true }
    ## rvm
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3', 'ruby-2.2'],
        rvm1_user: "{{ ansible_env.USER }}"
    }
    - { role: openshift-client }
    - { role: kubectl }
    - { role: s2i }
