---

- name: psunix desktop environment playbook
  hosts: localhost
  roles:
    - { role: profile, tags: ['profile'] }
    - { role: usb-utils, become: true, tags: ['usb-utils'] }
    - { role: nextcloud, become: true, tags: ['nextcloud'] }
    - { role: regolith, become: true , tags: ['regolith'] }
    - { role: kvm, become: true , tags: ['kvm'] }
    - { role: utils, become: true , tags: ['utils'] }
    - { role: msg-tools, become: true , tags: ['msg-tools'] }
    - { role: gfx, become: true , tags: ['gfx'] }
    # devel tools
    - { role: vim, become: true , tags: ['vim'] }
    - { role: firefox, become: true , tags: ['firefox'] }
    - { role: chromium, become: true , tags: ['chromium'] }
    - { role: audio, become: true , tags: ['audio'] }
    - { role: display, become: true , tags: ['display'] }
    - { role: docker, become: true , tags: ['docker'] }
    - { role: git, become: true , tags: ['git'] }
    # - { role: nitrokey, become: true , tags: ['nitrokey'] }
    - { role: ruby-dev-libs, become: true , tags: ['ruby-dev-libs'] }
    # nvm
    - { role: nvm,
        tags: nvm,
        nvm: { version: v0.33.11,
               node_version: 8.11.2,
               user: "{{ ansible_env.USER }}"
             }
    }
    - { role: openshift-client , tags: ['openshift-client'] }
    - { role: k8s-tools , tags: ['k8s-tools'] }
    - { role: s2i , tags: ['s2i'] }
    - { role: terminal , become: true, tags: ['terminal'] }
    - { role: astro, become: true , tags: ['astro'] }
    - { role: vagrant, become: true , tags: ['vagrant'] }
    - { role: office, become: true , tags: ['office'] }
    - { role: printer, become: true , tags: ['printer'] }
    - { role: dev-tools, become: true , tags: ['dev-tools'] }
