---

- name: psunix desktop environment playbook
  hosts: localhost
  roles:
    - { role: profile, tags: ['profile'] }
    - { role: usb-utils, become: true, tags: ['usb-utils'] }
    - { role: nextcloud, become: true, tags: ['nextcloud'] }
    - { role: i3, become: true , tags: ['i3'] }
    - { role: kvm, become: true , tags: ['kvm'] }
    # devel tools
    - { role: vim, become: true , tags: ['vim'] }
    - { role: firefox, become: true , tags: ['firefox'] }
    - { role: chromium, become: true , tags: ['chromium'] }
    - { role: audio, become: true , tags: ['audio'] }
    - { role: display, become: true , tags: ['display'] }
    - { role: docker, become: true , tags: ['docker'] }
    - { role: git, become: true , tags: ['git'] }
    - { role: nitrokey, become: true , tags: ['nitrokey'] }
    - { role: ruby-dev-libs, become: true , tags: ['ruby-dev-libs'] }
    # rvm
    - { role: rvm_io.ruby,
        tags: rvm,
        rvm1_rubies: ['ruby-2.3', 'ruby-2.2'],
        rvm1_user: "{{ ansible_env.USER }}"
    }
    # nvm
    - { role: nvm,
        tags: nvm,
        nvm: { version: v0.33.11,
               node_version: 8.11.2,
               user: "{{ ansible_env.USER }}"
             }
    }
    - { role: openshift-client , tags: ['openshift-client'] }
    - { role: kubectl , tags: ['kubectl'] }
    - { role: s2i , tags: ['s2i'] }
    - { role: terminal , become: true, tags: ['terminal'] }
