---
- name: install xfce terminal
  apt: pkg=xfce4-terminal state=latest

- name: xfce terminal settings directory
  become: true
  become_user: "{{ main_user }}"
  file:
    path: '~/.config/xfce4/terminal'
    state: directory

- name: xfce terminal settings
  become: true
  become_user: "{{ main_user }}"
  file:
    src: '~/git/setup/profile/xfce_terminal/terminalrc'
    dest: '~/.config/xfce4/terminal/terminalrc'
    state: link
    force: true
