---
- apt_repository:
    repo: ppa:yubico/stable
    state: present

- name: install yubikey manager
  apt: pkg=yubikey-manager state=latest

- name: install libpam yubico
  apt: pkg=libpam-yubico state=latest

- name: install yubico piv tool
  apt: pkg=yubico-piv-tool state=latest
